<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RevitAIClient</RootNamespace>
    <AssemblyName>RevitAIClient</AssemblyName>
    <!-- Отключаем генерацию папок с языковыми локализациями -->
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <!-- Отключаем создание папки net48 в bin/Debug -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <!-- Глобально отключаем копирование всех библиотек, на которые ссылаемся -->
  <ItemDefinitionGroup>
    <Reference>
      <Private>False</Private>
    </Reference>
    <ProjectReference>
      <Private>False</Private>
    </ProjectReference>
  </ItemDefinitionGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\..\..\..\Program Files\Autodesk\Revit 2023\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\..\..\..\Program Files\Autodesk\Revit 2023\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitUIAPI">
      <HintPath>..\..\..\..\Program Files\Autodesk\Revit 2023\RevitUIAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>